### ISSUE TITLE
blog 链接失效

### ISSUE THREAD

**Issue by MuYunyun** [ruoduan-hub/my-Gatsby-Blog#1]
http://new.ruoduan.cn/ 访问失效。

**Comment by ruoduan-hub** [comment]
> http://new.ruoduan.cn/访问无效。

new这个主机头弃用了 现在 直接 https://ruoduan.cn 就可以了

**Comment by fatFire** [comment]
> > [http://new.ruoduan.cn/访问无效。](http://new.ruoduan.cn/%E8%AE%BF%E9%97%AE%E6%97%A0%E6%95%88%E3%80%82)
> 
> new这个主机头弃用了 现在 直接 https://ruoduan.cn 就可以了

这个也无法访问了
