### ISSUE TITLE
有关于解决npm包中引用了全局window后报错的解决方案咨询

### ISSUE THREAD

**Issue by Anthony081105** [ruoduan-hub/my-Gatsby-Blog#3]
报错信息：WebpackError: ReferenceError: sessionStorage is not defined；
`// 忽略全局对象
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === "build-html") {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /xxx-xxxx/,
            use: loaders.null(),
          },
        ],
      },
    })
  }
}
`
这里rules中的test校验规则，如何才能将window的属性的这些报错忽略呢？我看你的代码写的是 [https://github.com/ruoduan-hub/my-Gatsby-Blog/blob/master/gatsby-node.js#L98-L117](url)
`rules: [
          {
            test: /react-cplayer/,
            use: loaders.null(),
          },
        ],`
我不是很明白为啥会写这个/react-cplayer/。
如果我想要解决这个问题，我这儿又该如何书写呢？望讲解，大佬

**Comment by ruoduan-hub** [comment]
#### because 

-  `react-cplayer` 这个包 内部使用了 在构建运行时不存在的对象 ——  例如 `window` 等；在不去给作者提pr更新去情况下 使用 `webpack` 的配置去忽略这个包

#### so

> 看样子是你构建的时候 使用了 `sessionStorage` 你可以 排查下是在什么地方使用的，如果是在项目内使用的话 `typeof`  可以解决，如果是内你所依赖包使用的话 可以通过 以下方法 解决 👇🏻

- [官方文档](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onCreateWebpackConfig)

``` js
exports.onCreateWebpackConfig = ({
 stage, getConfig, rules, loaders, actions
}) => {
  actions.setWebpackConfig({
    module: {
      rules: [
        {
          test: 'my-css',
          use: [loaders.style(), loaders.css()]
        },
      ],
    },
  });
}
```

**Comment by Anthony081105** [comment]
感谢！
